# P4

In [1]:
%load_ext autoreload

In [2]:
%autoreload 2
from src import eliminacion_gaussiana, gauss_jordan

A = [[1, 1, 0, 3, 4], [2, 1, -1, 1, 1], [3, -1, -1, 2, -3], [-1, 2, 3, -1, 4]]

r = eliminacion_gaussiana(A)
print(r,"---------")
gauss_jordan(A)


[08-13 10:01:15][INFO] 2024-08-13 10:01:15.686731
[08-13 10:01:15][INFO] 2024-08-13 10:01:15.856729
[08-13 10:01:15][INFO] 2024-08-13 10:01:15.858731
[08-13 10:01:15][INFO] 
[[  1   1   0   3   4]
 [  0  -1  -1  -5  -7]
 [  0  -4  -1  -7 -15]
 [  0   3   3   2   8]]
[08-13 10:01:15][INFO] 
[[  1   1   0   3   4]
 [  0  -1  -1  -5  -7]
 [  0   0   3  13  13]
 [  0   0   0 -13 -13]]
[08-13 10:01:15][INFO] 
[[  1   1   0   3   4]
 [  0  -1  -1  -5  -7]
 [  0   0   3  13  13]
 [  0   0   0 -13 -13]]
[-1.  2.  0.  1.] ---------
[08-13 10:01:15][INFO] 
[[  1   1   0   3   4]
 [  0  -1  -1  -5  -7]
 [  0  -4  -1  -7 -15]
 [  0   3   3   2   8]]
[08-13 10:01:15][INFO] 
[[  1   0  -1  -2  -3]
 [  0  -1  -1  -5  -7]
 [  0   0   3  13  13]
 [  0   0   0 -13 -13]]
[08-13 10:01:15][INFO] 
[[  1   0   0   2   1]
 [  0  -1   0   0  -2]
 [  0   0   3  13  13]
 [  0   0   0 -13 -13]]
[08-13 10:01:15][INFO] 
[[  1   0   0   0  -1]
 [  0  -1   0   0  -2]
 [  0   0   3   0   0]
 [  0   0   0 -13 -13]]


array([-1.,  2.,  0.,  1.])

In [3]:
A = [[1, -1, 2, -1, -8], [2, -2, 3, -3, -20], [1, 1, 1, 0, -2], [1, -1, 4, 3, 4]]

eliminacion_gaussiana(A)
r = eliminacion_gaussiana(A)
print(r, "---------")
gauss_jordan(A)

[08-13 10:01:15][INFO] 
[[ 1 -1  2 -1 -8]
 [ 0  0 -1 -1 -4]
 [ 0  2 -1  1  6]
 [ 0  0  2  4 12]]
[08-13 10:01:15][INFO] 
[[ 1 -1  2 -1 -8]
 [ 0  2 -1  1  6]
 [ 0  0 -1 -1 -4]
 [ 0  0  2  4 12]]
[08-13 10:01:15][INFO] 
[[ 1 -1  2 -1 -8]
 [ 0  2 -1  1  6]
 [ 0  0 -1 -1 -4]
 [ 0  0  0  2  4]]
[08-13 10:01:15][INFO] 
[[ 1 -1  2 -1 -8]
 [ 0  0 -1 -1 -4]
 [ 0  2 -1  1  6]
 [ 0  0  2  4 12]]
[08-13 10:01:16][INFO] 
[[ 1 -1  2 -1 -8]
 [ 0  2 -1  1  6]
 [ 0  0 -1 -1 -4]
 [ 0  0  2  4 12]]
[08-13 10:01:16][INFO] 
[[ 1 -1  2 -1 -8]
 [ 0  2 -1  1  6]
 [ 0  0 -1 -1 -4]
 [ 0  0  0  2  4]]
[-7.  3.  2.  2.] ---------
[08-13 10:01:16][INFO] 
[[ 1 -1  2 -1 -8]
 [ 0  0 -1 -1 -4]
 [ 0  2 -1  1  6]
 [ 0  0  2  4 12]]
[08-13 10:01:16][INFO] 
[[ 1  0  1  0 -5]
 [ 0  2 -1  1  6]
 [ 0  0 -1 -1 -4]
 [ 0  0  2  4 12]]
[08-13 10:01:16][INFO] 
[[ 1  0  0 -1 -9]
 [ 0  2  0  2 10]
 [ 0  0 -1 -1 -4]
 [ 0  0  0  2  4]]
[08-13 10:01:16][INFO] 
[[ 1  0  0  0 -7]
 [ 0  2  0  0  6]
 [ 0  0 -1  0 -2]
 [ 0  0  0  2  4]]


array([-7.,  3.,  2.,  2.])

In [4]:
import numpy as np
import logging
from sys import stdout
from datetime import datetime

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s][%(levelname)s] %(message)s",
    stream=stdout,
    datefmt="%m-%d %H:%M:%S",
)
logging.info(datetime.now())

[08-13 10:01:16][INFO] 2024-08-13 10:01:16.119730


In [5]:
# ####################################################################
def inv_matrix(A: np.ndarray) -> np.ndarray:
    """Inversión de una matriz cuadrada mediante eliminación de Gauss-Jordan.
    ## Parameters
    ``A``: matriz cuadrada de tamaño n x n.

    ## Return
    ``A_inv``: matriz inversa de A.
    """
    if not isinstance(A, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        A = np.array(A)
    assert A.shape[0] == A.shape[1], "La matriz A debe ser cuadrada."
    n = A.shape[0]
    # ---- extebder matriz
    A = np.hstack([A, np.eye(n)])
    for i in range(0, n):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if A[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(A[pi, i]) < abs(A[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            raise ValueError("No existe solución única.")

        if p != i:
            # swap rows
            logging.debug(f"Intercambiando filas {i} y {p}")
            _aux = A[i, :].copy()
            A[i, :] = A[p, :].copy()
            A[p, :] = _aux

        # --- Eliminación: loop por fila
        for j in range(n):
            if i == j:
                continue
            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]

        logging.info(f"\n{A}")

    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

    # --- Simplificación
    for i in range(n):
        A[i, n:] = A[i, n:] / A[i, i]
        A[i, i] = 1

    return A[:, n:]

In [6]:
A = [
    [1, 2, 3, 4],
    [2, 5, 6, 7],
    [3, 6, 8, 9],
    [4, 7, 9, 10],
]
inv_matrix(A)

[08-13 10:01:16][INFO] 
[[ 1.  2.  3.  4.  1.  0.  0.  0.]
 [ 0.  1.  0. -1. -2.  1.  0.  0.]
 [ 0.  0. -1. -3. -3.  0.  1.  0.]
 [ 0. -1. -3. -6. -4.  0.  0.  1.]]
[08-13 10:01:16][INFO] 
[[ 1.  0.  3.  6.  5. -2.  0.  0.]
 [ 0.  1.  0. -1. -2.  1.  0.  0.]
 [ 0.  0. -1. -3. -3.  0.  1.  0.]
 [ 0.  0. -3. -7. -6.  1.  0.  1.]]
[08-13 10:01:16][INFO] 
[[ 1.  0.  0. -3. -4. -2.  3.  0.]
 [ 0.  1.  0. -1. -2.  1.  0.  0.]
 [ 0.  0. -1. -3. -3.  0.  1.  0.]
 [ 0.  0.  0.  2.  3.  1. -3.  1.]]
[08-13 10:01:16][INFO] 
[[ 1.   0.   0.   0.   0.5 -0.5 -1.5  1.5]
 [ 0.   1.   0.   0.  -0.5  1.5 -1.5  0.5]
 [ 0.   0.  -1.   0.   1.5  1.5 -3.5  1.5]
 [ 0.   0.   0.   2.   3.   1.  -3.   1. ]]


array([[ 0.5, -0.5, -1.5,  1.5],
       [-0.5,  1.5, -1.5,  0.5],
       [-1.5, -1.5,  3.5, -1.5],
       [ 1.5,  0.5, -1.5,  0.5]])

In [7]:
A = [[1, 1, 0, 3], [2, 1, -1, 1], [3, -1, -1, 2], [-1, 2, 3, -1]]
A = [
    [4, 4, 5, 1],
    [3, 4, 2, 2],
    [2, 1, 4, 1],
    [3, 2, 5, 4],
]
A = [
    [0, 0, 0, 0, 0, 0, 1, -1],
    [0, 1, -1, 1, 0, -1, 0, 1],
    [-1, -1, 0, 0, 2, 1, 0, 0],
    [-1, -1, -1, 1, 2, 0, 0, 1],
    [-1, 1, 1, 0, -1, -1, 0, 2],
    [0, 1, 0, 0, -1, -1, 0, 0],
    [1, -1, -1, 1, 2, 1, 0, 2],
    [2, 0, 0, 0, 0, 1, 2, 0],
]
# A = [
#     [1, 1, 1, 0, 1, 1, 1, 1, 0, -1, -1, 0],
#     [0, 1, -1, 0, 0, 0, 0, 1, 1, -1, -1, 0],
#     [-1, 0, -1, -1, -1, -1, -1, -1, 0, 1, -1, 0],
#     [-1, -1, 0, 1, 0, 0, -1, 1, 1, -1, 1, 0],
#     [1, 1, 0, 0, 0, 0, 1, -1, 1, 0, 1, 0],
#     [0, 0, 1, 0, 1, 0, 0, -1, 0, -1, 1, 1],
#     [0, 0, 1, 1, 0, 0, -1, 0, 0, 1, -1, 1],
#     [0, 0, 0, 1, 1, 1, 1, 1, 1, -1, 1, -1],
#     [0, -1, 0, 0, -1, 1, 0, 1, -1, 1, -1, 1],
#     [1, 1, -1, 0, 1, 0, 1, -1, 0, 1, -1, 0],
#     [0, 0, 1, 1, 1, 1, 0, 0, -1, -1, 0, 1],
#     [-1, 0, 0, 1, 1, -1, -1, 0, 0, -1, 1, -1],
# ]
w = inv_matrix(A)
w

[08-13 10:01:16][INFO] 
[[-1. -1.  0.  0.  2.  1.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  1. -1.  1.  0. -1.  0.  1.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1. -1.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  1.  0. -1.  0.  1.  0.  0. -1.  1.  0.  0.  0.  0.]
 [ 0.  2.  1.  0. -3. -2.  0.  2.  0.  0. -1.  0.  1.  0.  0.  0.]
 [ 0.  1.  0.  0. -1. -1.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0. -2. -1.  1.  4.  2.  0.  2.  0.  0.  1.  0.  0.  0.  1.  0.]
 [ 0. -2.  0.  0.  4.  3.  2.  0.  0.  0.  2.  0.  0.  0.  0.  1.]]
[08-13 10:01:16][INFO] 
[[-1.  0. -1.  1.  2.  0.  0.  1.  0.  1.  1.  0.  0.  0.  0.  0.]
 [ 0.  1. -1.  1.  0. -1.  0.  1.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1. -1.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  1.  0. -1.  0.  1.  0.  0. -1.  1.  0.  0.  0.  0.]
 [ 0.  0.  3. -2. -3.  0.  0.  0.  0. -2. -1.  0.  1.  0.  0.  0.]
 [ 0.  0.  1. -1. -1.  0.  0. -1.  0. -1.  0.  0.  0.  1.  0.  0.]
 [ 0.  0. -3.

array([[ 2., -1., -0., -1., -0.,  2.,  2., -1.],
       [ 0.,  1.,  1., -1.,  0.,  0.,  0.,  0.],
       [ 6., -1., -0., -3.,  1.,  1.,  4., -3.],
       [ 6.,  1., -1., -3.,  1., -3.,  3., -3.],
       [ 2., -1.,  1., -1., -0.,  3.,  2., -1.],
       [-2.,  2., -0., -0., -0., -4., -2.,  1.],
       [-1.,  0.,  0.,  1.,  0.,  0., -1.,  1.],
       [-2.,  0.,  0.,  1.,  0.,  0., -1.,  1.]])

In [8]:
A = [
    [1, 0, 0, 0, -1, 0, 0, -1, 1, -1],
    [1, 1, 0, -1, -1, 1, 0, 0, 1, -1],
    [-1, 0, -1, 0, 0, 0, -1, 1, 0, 0],
    [0, 0, -1, 0, -1, -1, 1, 0, 1, 0],
    [-1, 0, 0, -1, 1, 1, 1, 1, 0, -1],
    [1, 0, 0, 1, -1, -1, -1, 1, -1, 0],
    [1, 1, 1, 0, 1, 0, -1, -1, -1, 1],
    [1, 1, 1, 1, 0, 0, 1, 1, 0, 0],
    [1, 1, 1, 1, 1, 0, -1, -1, 0, 0],
    [0, 0, -1, -1, -1, 0, 1, 1, 1, -1],
]
w = inv_matrix(A)
w

[08-13 10:01:16][INFO] 
[[ 1.  0.  0.  0. -1.  0.  0. -1.  1. -1.  1.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  1.  0. -1.  0.  1.  0.  1.  0.  0. -1.  1.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0. -1.  0. -1.  0. -1.  0.  1. -1.  1.  0.  1.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0. -1.  0. -1. -1.  1.  0.  1.  0.  0.  0.  0.  1.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0. -1.  0.  1.  1.  0.  1. -2.  1.  0.  0.  0.  1.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  1.  0. -1. -1.  2. -2.  1. -1.  0.  0.  0.  0.  1.  0.  0.
   0.  0.]
 [ 0.  1.  1.  0.  2.  0. -1.  0. -2.  2. -1.  0.  0.  0.  0.  0.  1.  0.
   0.  0.]
 [ 0.  1.  1.  1.  1.  0.  1.  2. -1.  1. -1.  0.  0.  0.  0.  0.  0.  1.
   0.  0.]
 [ 0.  1.  1.  1.  2.  0. -1.  0. -1.  1. -1.  0.  0.  0.  0.  0.  0.  0.
   1.  0.]
 [ 0.  0. -1. -1. -1.  0.  1.  1.  1. -1.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  1.]]
[08-13 10:01:16][INFO] 
[[ 1.  0.  0.  0. -1.  0.  0. -1.  1. -1.  1.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  1.  0. -1

array([[ 14.,  -8.,   9.,  -4.,   0.,  -4.,   9.,   7.,  -8.,   3.],
       [ -2.,   2.,  -1.,   2.,   1.,   1.,  -1.,  -1.,   1.,  -2.],
       [-27.,  14., -18.,   5.,  -2.,   7., -17., -13.,  16.,  -2.],
       [ 12.,  -6.,   8.,  -2.,   1.,  -3.,   7.,   6.,  -7.,  -0.],
       [  6.,  -4.,   4.,  -2.,   0.,  -2.,   4.,   3.,  -3.,   2.],
       [ 18.,  -9.,  12.,  -4.,   1.,  -5.,  11.,   9., -11.,   1.],
       [  8.,  -4.,   5.,  -1.,   1.,  -2.,   5.,   4.,  -5.,  -0.],
       [ -5.,   2.,  -3.,   0.,  -1.,   1.,  -3.,  -2.,   3.,   1.],
       [-11.,   5.,  -7.,   1.,  -2.,   2.,  -7.,  -5.,   7.,   1.],
       [  1.,  -1.,   1.,  -1.,  -1.,  -1.,   1.,   1.,  -1.,   1.]])

In [9]:
w[5, -1]

1.0

In [10]:
A = [
    [4, 0, 0, 5],
    [1, 0, 4, 0],
    [3, 4, 1, 3],
    [1, 3, 3, 0],
]
inv_matrix(A)

[08-13 10:01:16][INFO] 
[[  1.   0.   4.   0.   0.   1.   0.   0.]
 [  0.   0. -16.   5.   1.  -4.   0.   0.]
 [  0.   4. -11.   3.   0.  -3.   1.   0.]
 [  0.   3.  -1.   0.   0.  -1.   0.   1.]]
[08-13 10:01:16][INFO] 
[[  1.           0.           4.           0.           0.
    1.           0.           0.        ]
 [  0.           3.          -1.           0.           0.
   -1.           0.           1.        ]
 [  0.           0.          -9.66666667   3.           0.
   -1.66666667   1.          -1.33333333]
 [  0.           0.         -16.           5.           1.
   -4.           0.           0.        ]]
[08-13 10:01:16][INFO] 
[[ 1.          0.          0.          1.24137931  0.          0.31034483
   0.4137931  -0.55172414]
 [ 0.          3.          0.         -0.31034483  0.         -0.82758621
  -0.10344828  1.13793103]
 [ 0.          0.         -9.66666667  3.          0.         -1.66666667
   1.         -1.33333333]
 [ 0.          0.          0.          0.034482

array([[-36.,  45.,  60., -80.],
       [  3.,  -4.,  -5.,   7.],
       [  9., -11., -15.,  20.],
       [ 29., -36., -48.,  64.]])

In [11]:
np.linalg.inv(A)

array([[-36.,  45.,  60., -80.],
       [  3.,  -4.,  -5.,   7.],
       [  9., -11., -15.,  20.],
       [ 29., -36., -48.,  64.]])

In [12]:
A = [[1, 1, 0, 3], [2, 1, -1, 1], [3, -1, -1, 2], [-1, 2, 3, -1]]
# A = [
#     [1, 2, 3, 4],
#     [2, 5, 6, 7],
#     [3, 6, 8, 9],
#     [4, 7, 9, 10],
# ]
A = [
    [4, 4, 5, 1],
    [3, 4, 2, 2],
    [2, 1, 4, 1],
    [3, 2, 5, 4],
]

np.linalg.inv(A)

array([[-34.,  31.,  52., -20.],
       [ 19., -17., -29.,  11.],
       [ 12., -11., -18.,   7.],
       [  1.,  -1.,  -2.,   1.]])